### ISSUE TITLE
problem with NASADEM in merging_glaciers.ipynb

### ISSUE THREAD

**Issue by lilianschuster** [OGGM/tutorials#10]
When calling workflow.merge_glacier_tasks() in the  [merging_glaciers.ipynb](https://oggm.org/tutorials/notebooks/merging_glaciers.html), there is again the HttpDownloaderror because of NASADEM if you have not registered at Earthdata ....

I did not find a way to switch the DEM here, otherwise we could say at the beginning that the notebook can only run when having done the registration?

**Comment by lilianschuster** [comment]
same NASADEM problem occurs in [use_your_own_inventory.ipynb](https://oggm.org/tutorials/notebooks/use_your_own_inventory.html#run-oggm-with-this-new-glacier) during `execute_entity_task(tasks.define_glacier_region, gdirs)`.

For this notebook, however, we could just use instead `execute_entity_task(tasks.define_glacier_region, gdirs, source = 'SRTM')`, then the notebook runs!

**Comment by fmaussion** [comment]
Thanks for the heads up - can you please fix the use_your_own_inventory one? I'll have a look at the merging_glacier one
