### ISSUE TITLE
Issue on page /book/construction.html

### ISSUE THREAD

**Issue by Dansgethb** [OGGM/tutorials#134]
Your issue content here.
I realize this could be a big ask, but my whole purpose in employing this tool is to model combined, interactive, co-potentiating risk/failure scenarios for a global risk factor.  In other words, it is important to model in the potential for one failure (or even simple significant rise) as a trigger for other glacier failures.

**Comment by pat-schmitt** [comment]
Could you specify the issue you are encountering?
