### ISSUE TITLE
`ModuleNotFoundError: No module named 'oggm_edu'`

### ISSUE THREAD

**Issue by kimcholi** [OGGM/tutorials#25]
Hello everybody,

I'm fairly new to using OGGM. Therefore I am currently working through the OGGM tutorials. I tried the tutorial on Hydrological mass-balance output. The following error came up: `ModuleNotFoundError: No module named 'oggm_edu'`. I have already updated OGGM, I've tried to install the package via `conda install -c anaconda oggm_edu -y`, which unfortunately did not work, and I've tried to download the dependies again via `conda install -c oggm -c conda-forge oggm-deps` but it told me that all requested packages are already installed.

Thank you!
![Bildschirmfoto 2021-06-28 um 9 47 40 AM (2)](https://user-images.githubusercontent.com/85988565/123599879-6157c200-d7f6-11eb-90d4-e2db010930e5.png)

**Comment by fmaussion** [comment]
Transferred to tutorials repository. These imports need to be removed.

**Comment by kimcholi** [comment]
Thank you very much! I removed the imports as well as `from oggm_edu import read_run_results, compute_climate_statistics` and it all worked.
