### ISSUE TITLE
New Workflow Tutorial (how to merge output of different projection runs and visualize)

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/tutorials#31]
I will work on a new tutorial notebook in which I will show how to merge the output of different projection runs (different RCPs and different GCMs for a selection of glaciers) into one `xarray.Dataset`. And further (maybe in a second notebook) how to create interactive plots using this new 'complete' Dataset (e.g. yearly evolution of total volume (mean and std of all GCMs), monthly hydro output for different periods, ...)

**Comment by fmaussion** [comment]
Awesome!!!! Thanks a lot
