### ISSUE TITLE
problem with tasks.define_glacier_region

### ISSUE THREAD

**Issue by lilianschuster** [OGGM/tutorials#8]
In the [dem_sources.ipynb](https://oggm.org/tutorials/notebooks/dem_sources.html), the `tasks.define_glacier_region(gdir)` did not work for me. It gives an HTTPDownloadError for this link: [(https://e4ftl01.cr.usgs.gov/MEASURES/NASADEM_HGT.001/2000.02.11/NASADEM_HGT_n46e010.zip]. Does

I think one has to give the Earthdata Login credentials. Should we change the source to 'SRTM' for the tutorial as this needs no registering?

**Comment by fmaussion** [comment]
Yes! Good catch!
